name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Check file structure
        run: |
          echo "Verificando estrutura de arquivos..."
          
          # Verifica se os diretórios essenciais existem
          for dir in docs scripts templates; do
            if [ ! -d "$dir" ]; then
              echo "❌ Erro: Diretório $dir não encontrado"
              exit 1
            else
              echo "✅ Diretório $dir encontrado"
            fi
          done
          
          # Verifica se os arquivos essenciais existem
          essential_files=(
            "README.md"
            "docs/INSTRUCTIONS.md"
            "docs/INSTRUCTIONS_PART1.md"
            "docs/INSTRUCTIONS_PART2.md"
            "templates/project-status.json"
          )
          
          for file in "${essential_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Erro: Arquivo $file não encontrado"
              exit 1
            else
              echo "✅ Arquivo $file encontrado"
            fi
          done
          
          echo "Estrutura de arquivos verificada com sucesso!"
      
      - name: Validate JSON files
        run: |
          echo "Validando arquivos JSON..."
          
          # Lista todos os arquivos JSON no repositório
          json_files=$(find . -name "*.json" -type f)
          
          # Verifica se cada arquivo é um JSON válido
          for file in $json_files; do
            if ! jq empty "$file" 2>/dev/null; then
              echo "❌ Erro: $file não é um JSON válido"
              exit 1
            else
              echo "✅ $file é um JSON válido"
            fi
          done
          
          echo "Todos os arquivos JSON são válidos!"
      
      - name: Check JavaScript syntax
        run: |
          echo "Verificando sintaxe de arquivos JavaScript..."
          
          # Lista todos os arquivos JavaScript no repositório
          js_files=$(find . -name "*.js" -type f)
          
          # Verifica a sintaxe de cada arquivo JS
          for file in $js_files; do
            if ! node --check "$file"; then
              echo "❌ Erro de sintaxe em $file"
              exit 1
            else
              echo "✅ $file tem sintaxe válida"
            fi
          done
          
          echo "Todos os arquivos JavaScript têm sintaxe válida!"

  combine-instructions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install fs-extra
      
      - name: Combine instructions
        run: node .github/scripts/run_combine.js
      
      - name: Check if INSTRUCTIONS.md was updated
        run: |
          if git diff --quiet docs/INSTRUCTIONS.md; then
            echo "✅ INSTRUCTIONS.md está atualizado"
          else
            echo "❌ INSTRUCTIONS.md não está sincronizado com as partes"
            git diff docs/INSTRUCTIONS.md
            exit 1
          fi
